#!/bin/bash
# Make sure you are on the most updated branch (here it's master) before you run this!

git rebase server_runs

git checkout server_runs

git merge master

git checkout master # and go back to master branch
