#!/bin/bash
# Instead of master, you can use the "better branch" which you want to overwrite the server_runs branch with

git checkout server_runs

git reset --hard master

git push -f origin server_runs

git checkout master # and go back to master branch
