#!/bin/bash

git checkout server_runs 2>/dev/null || git checkout -b server_runs

git push --set-upstream origin server_runs

git add .

git commit -m "update for server run"

git push

git checkout master
