#!/bin/bash

#SBATCH -J scheduler_training_ae_model_augmented_autodiff
#SBATCH -p gtx
#SBATCH -N 4
#SBATCH --ntasks-per-node=5
#SBATCH -t 24:00:00
#SBATCH -o scheduler_training_ae_model_augmented_autodiff.out
#SBATCH --mail-user=Hwan.Goh@gmail.com
#SBATCH --mail-type=all

module load intel/18.0.2 python3/3.7.0 cuda/10.1 cudnn/7.6.5 nccl/2.5.6
ibrun ./scheduler_multinode_distributed_process_training_ae.py
