#!/bin/bash

#SBATCH -J AEFwdInv_Scheduled_2D_vary_full_bnd
#SBATCH -p gtx
#SBATCH -N 1
#SBATCH -n 5
#SBATCH -t 24:00:00
#SBATCH -o AEFwdInv_Scheduled_2D_vary_full_bnd.out
#SBATCH --mail-user=Hwan.Goh@gmail.com
#SBATCH --mail-type=all

module load intel/17.0.4 python3/3.6.3 cuda/10.0 cudnn/7.6.2 nccl/2.4.7

ibrun -np 5 python3 Scheduler_Training_Autoencoder_Fwd_Inv.py
