#!/bin/bash

#SBATCH -J scheduler_training_ae_model_augmented_autodiff
#SBATCH -p normal
#SBATCH -N 16
#SBATCH --ntasks-per-node=2
#SBATCH -t 48:00:00
#SBATCH -o scheduler_training_ae_model_augmented_autodiff.out
#SBATCH --mail-user=Hwan.Goh@gmail.com
#SBATCH --mail-type=all

module load intel/18.0.2 python3/3.7.0
ibrun ./scheduler_cpu_multinode_distributed_process_training_ae.py
